/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_PaqueteRPC (XDR *xdrs, PaqueteRPC *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_VectorFloat (XDR *xdrs, VectorFloat *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->VectorFloat_val, (u_int *) &objp->VectorFloat_len, MAX_N_VALUE2,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SetModifyArgs (XDR *xdrs, SetModifyArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, MAX_KEY_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_VALUE1_LEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_VectorFloat (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetValueResult (XDR *xdrs, GetValueResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->resultado))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_VALUE1_LEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_VectorFloat (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
